# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63aab6efeb0e12d4c553d621bacc6436a1a9f448541e8fd5dc9ed6e44f382e8951d524f335ead5a12a8624de21d11155c6edd1ad26ca23b4ece6a236f5ffd4b6

test:
  secret_key_base: b3e11f72e19a203809d0a26f0a8348b8249bef98b8487b7ad80f214d0f59639e76aa8adf4755e120d1aaaa5904856a202b226f77bd78974ca2063bf32499f55a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
